name: Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the actions branch
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions

jobs:
  run-build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run build
        run: |
          npm run build

        # https://github.community/t/how-does-one-commit-from-an-action/16127/10
      - name: Commit built files
      - uses: actions/checkout@v3
      - run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add .
          git commit -m "Built project"
          git push
