name: Push new version to dist branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the actions branch
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions

jobs:
  deploy:
    name: Push new version to dist branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Use Node.js
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16.x
    - name: Run build
      run: |
        npm run build

    - name: Push new version
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
